name: ${name}
id: ${id}
main: ${group}.platform.spigot.AuraSudoSpigotBootstrap
version: ${version}
author: BrainStone
description: ${description}
url: https://github.com/AuraDevelopmentTeam/AuraSudo
depends:
  - LuckPerms
